### ISSUE TITLE
Add Commerce logo

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/business-technical-support-finder#1]
![Commerce-Logo-Phila](https://user-images.githubusercontent.com/10891276/67690920-20017600-f974-11e9-8717-ac443596d11a.png) @karissademi

**Comment by karissademi** [comment]
I got it from Stacy, thanks! 

Closed in https://github.com/CityOfPhiladelphia/business-technical-support-finder/commit/bba35651a503582b85c6dfd5bbd8bcd066ff1b4b.
